"""Generate Markdown QA reports from style diffs."""

import os
from datetime import datetime
from collections import defaultdict
from pathlib import Path

from diff_styles import StyleDiff


def generate_report(
    page_name: str,
    sections: list[dict],
    all_diffs: list[StyleDiff],
    viewports: list[int],
    tolerance: int,
    flags: list[str],
    screenshot_dir: str | None = None,
) -> str:
    """Generate a Markdown report for a single page."""
    now = datetime.now()
    viewport_str = ", ".join(f"{v}px" for v in viewports)
    flags_str = " ".join(flags) if flags else "none"

    counts = defaultdict(int)
    for d in all_diffs:
        counts[d.severity] += 1

    lines = []
    lines.append(f"# Visual QA Report: {page_name}")
    lines.append(f"**Date:** {now.strftime('%Y-%m-%d %H:%M')} | **Viewports:** {viewport_str}")
    lines.append(f"**Tolerance:** {tolerance}px | **Flags:** {flags_str}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    summary_parts = []
    for sev in ["Critical", "Notable", "Marginal", "Unknown"]:
        if counts[sev] > 0:
            summary_parts.append(f"{sev}: {counts[sev]}")
    if summary_parts:
        lines.append("- " + " | ".join(summary_parts))
    else:
        lines.append("- No issues found!")
    lines.append("")

    # Unknown selectors (prominent)
    unknowns = [d for d in all_diffs if d.severity == "Unknown"]
    if unknowns:
        lines.append("### Unknown Selectors (config may be stale)")
        lines.append("")
        lines.append("| Element | Selector | Viewport | Details |")
        lines.append("|---------|----------|----------|---------|")
        for d in unknowns:
            lines.append(f"| {d.element_name} | `{d.element_selector}` | {d.viewport}px | {d.actual} |")
        lines.append("")

    # Group diffs by section (using section_name tagged during audit)
    section_diffs = defaultdict(list)
    for d in all_diffs:
        if d.severity == "Unknown":
            continue
        section_diffs[d.section_name].append(d)

    # Render each section
    for sec in sections:
        sec_name = sec["name"]
        diffs = section_diffs.get(sec_name, [])

        lines.append(f"## {sec_name}")
        theme_file = sec.get("themeFile", "")
        if theme_file:
            lines.append(f"**Theme file:** `theme/{theme_file}`")

        if screenshot_dir:
            slug = sec_name.lower().replace(" ", "-")
            lines.append(f"**Screenshots:** `{screenshot_dir}/{page_name.lower()}-{slug}-*.png` (section-level)")

        lines.append("")

        if not diffs:
            lines.append("No issues found.")
            lines.append("")
            continue

        # Group by category, then viewport
        cat_viewport_diffs = defaultdict(lambda: defaultdict(list))
        for d in diffs:
            cat_viewport_diffs[d.category][d.viewport].append(d)

        for category in [
            "Typography", "Sizes & Spacing", "Layout & Positioning",
            "Images", "Icons & SVGs", "Backgrounds & Visual", "Other"
        ]:
            if category not in cat_viewport_diffs:
                continue

            for viewport in sorted(cat_viewport_diffs[category].keys(), reverse=True):
                vp_diffs = cat_viewport_diffs[category][viewport]
                lines.append(f"### {category} ({viewport}px)")
                lines.append("")
                lines.append("| Element | Property | Expected | Actual | Severity |")
                lines.append("|---------|----------|----------|--------|----------|")
                for d in vp_diffs:
                    lines.append(
                        f"| `{d.element_selector}` | {d.property} | `{d.expected}` | `{d.actual}` | {d.severity} |"
                    )
                lines.append("")

    lines.append("---")
    lines.append("*Generated by visual-qa skill. Run again after fixes to verify.*")
    lines.append("")

    return "\n".join(lines)


def save_report(
    content: str,
    page_name: str,
    output_dir: str = "docs/qa-reports",
) -> str:
    """Save report to file. Returns the file path."""
    os.makedirs(output_dir, exist_ok=True)
    now = datetime.now()
    slug = page_name.lower().replace(" ", "-")
    filename = f"visual-qa-{slug}-{now.strftime('%Y-%m-%d-%H%M')}.md"
    filepath = os.path.join(output_dir, filename)
    Path(filepath).write_text(content, encoding="utf-8")
    return filepath
